<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-EILEJI2A" failures="3" tests="4" name="bankingAppTest(failed)(failed)" time="31.852" errors="0" timestamp="2023-04-10T18:49:03 IST">
  <testcase classname="com.banking.testCases.TC_loginDataDrivenTest_002" name="loginDDTest" time="3.559">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.banking.testCases.TC_loginDataDrivenTest_002.loginDDTest(TC_loginDataDrivenTest_002.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDTest -->
  <testcase classname="com.banking.testCases.TC_loginDataDrivenTest_002" name="loginDDTest" time="3.158">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.banking.testCases.TC_loginDataDrivenTest_002.loginDDTest(TC_loginDataDrivenTest_002.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDTest -->
  <testcase classname="com.banking.testCases.TC_loginDataDrivenTest_002" name="loginDDTest" time="2.094">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.banking.testCases.TC_loginDataDrivenTest_002.loginDDTest(TC_loginDataDrivenTest_002.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDTest -->
  <testcase classname="com.banking.testCases.TC_loginTest_001" name="loginTest" time="2.394"/>
</testsuite> <!-- bankingAppTest(failed)(failed) -->
